### ISSUE TITLE
Normalizing the text often removes the last word of one sentence

### ISSUE THREAD

**Issue by 121898** [EFord36/normalise#123]
I tried to normalize the text using this toolkit, I found that it's very common that the last word is removed.

For instance, if the input is

> On the 13 Feb. 2007, Rt. Hon. Theresa May MP announced on ITV News that the rate of childhod obesity had risen from 7.3-9.6% in just 3 years, costing the Gov. £20m 

The final "£20m " will be removed, and the results will be

>['On', 'the', 'thirteenth of', 'February', 'two thousand and seven', ',', 'right', 'Honourable', 'Theresa', 'May', 'M P', 'announced', 'on', 'I T V', 'News', 'that', 'the', 'rate', 'of', 'childhood', 'obesity', 'had', 'risen', 'from', 'seven point three to nine point six percent', 'in', 'just', 'three', 'years', ',', 'costing', 'the', 'government', 'twenty million pounds', '.']

If multiple sentences are input, it can happen that the last word of each sub-sentence is removed

**Comment by EFord36** [comment]
Hi,

Sorry for the slow response on this. I'm not actively maintaining this repository currently, but I may be able to help with bugs.

I'm not sure what you mean from the example - in this case £20m has been normalised to 'twenty million pounds' rather than removed. Do you have an example with multiple sentences? I'm aware it's been several months since you opened the issue so you may not have an example anymore - sorry if that's the case for not getting back to you earlier.

**Comment by EFord36** [comment]
Without an example, I'm going to close this ticket for now, but feel free to re-open if you have one.
